### ISSUE TITLE
Glance over on-screen area is of top of file

### ISSUE THREAD

**Issue by AlexBlandin** [olmokramer/atom-minimap-codeglance#33]
When I glance over the minimap for the code that's currently on-screen, it shows the top of the file instead of either the current code or nothing at all (it is already on the screen, so I don't really need to glance at it, having an option for that would be sweet)

**Comment by cnsumner** [comment]
I noticed this too.  Does anyone know how long this has been an issue?  Or where in the code to start fixing it.

**Comment by ryaninvents** [comment]
I was able to kludge a fix locally. In `minimap-codeglance.js`, insert the following lines [after the first line](https://github.com/olmokramer/atom-minimap-codeglance/blob/master/lib/minimap-codeglance.js#L120) of the `scrollToMinimapOffset` method:

```js
    var {offsetX, offsetY, target} = event
    var correctedEvent = {offsetX, offsetY}
    if (target.className === 'minimap-visible-area') {
      var transform = new WebKitCSSMatrix(window.getComputedStyle(target).webkitTransform)
      correctedEvent.offsetY += transform.m42
    }
    event = correctedEvent
```

What's happening is that the event stores the mouse's position relative to the hovered element. When you mouse over the visible area of the minimap, then that visible area is the hovered element. For instance, if the visible area is halfway down the full minimap, and you mouse over the top of the visible area, the `offsetY` jumps to 0 since the mouse is at the top of the element that caught the mouseover.

To correct this, we need to read the visible area's position relative to its parent, but minimap uses a CSS transform to set the position of the visible area. That's why we need to use `WebKitCSSMatrix` to read that value out.

I might prepare a PR soon with a less-hacky way of writing this.

**Comment by nabaxo** [comment]
This bug is back.

**Comment by kifirkin** [comment]
@ryaninvents Your solution works like a charm! Is there a possibility to make a nice PR for this fix?

**Comment by tobiasvl** [comment]
This annoys me too, a PR would be great. Is this package maintained?

**Comment by davisonio** [comment]
@tobiasvl Happy to merge any PR, not making any active fixes to this though

**Comment by tobiasvl** [comment]
@davisonio @ryaninvents Thanks a lot! Will there be a new release too?
